<?php declare(strict_types=1);

namespace Tolkam\ImageManager;

use Tolkam\ImageManager\Variation\VariationManager;
use Tolkam\UriGenerator\GeneratorStrategyInterface;

/**
 * Applies provided uri generation strategy to
 * resource name generated by variation manager
 *
 * @package Tolkam\ImageManager
 */
class UriGeneratorVariationStrategy implements GeneratorStrategyInterface
{
    /**
     * @var VariationManager
     */
    protected VariationManager $variationManager;
    
    /**
     * @var string
     */
    protected string $variationAlias;
    
    /**
     * @var GeneratorStrategyInterface
     */
    protected GeneratorStrategyInterface $strategyToApply;
    
    /**
     * @param VariationManager           $variationManager
     * @param string                     $variationAlias
     * @param GeneratorStrategyInterface $strategyToApply
     */
    public function __construct(
        VariationManager $variationManager,
        string $variationAlias,
        GeneratorStrategyInterface $strategyToApply
    ) {
        $this->variationManager = $variationManager;
        $this->variationAlias = $variationAlias;
        $this->strategyToApply = $strategyToApply;
    }
    
    /**
     * @inheritDoc
     */
    public function apply(string $resourceName): string
    {
        return $this->strategyToApply->apply(
            $this->variationManager->getVFL($resourceName, $this->variationAlias)
        );
    }
}
